//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportEvents.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportEvents.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All groups.
        /// </summary>
        public static string allGroups {
            get {
                return ResourceManager.GetString("allGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed characters are a-z, A-Z and 0-9 with a minimum length of 8 characters..
        /// </summary>
        public static string allowedCharacters {
            get {
                return ResourceManager.GetString("allowedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login page.
        /// </summary>
        public static string backList {
            get {
                return ResourceManager.GetString("backList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the list of groups..
        /// </summary>
        public static string backListGroup {
            get {
                return ResourceManager.GetString("backListGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string badPassword {
            get {
                return ResourceManager.GetString("badPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change credential.
        /// </summary>
        public static string changeCredential {
            get {
                return ResourceManager.GetString("changeCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change of password.
        /// </summary>
        public static string changedPassword {
            get {
                return ResourceManager.GetString("changedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the confirmation password..
        /// </summary>
        public static string completePassword {
            get {
                return ResourceManager.GetString("completePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My created groups.
        /// </summary>
        public static string createdGroup {
            get {
                return ResourceManager.GetString("createdGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a group.
        /// </summary>
        public static string createGroup {
            get {
                return ResourceManager.GetString("createGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group.
        /// </summary>
        public static string editGroup {
            get {
                return ResourceManager.GetString("editGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email(Login).
        /// </summary>
        public static string emailLog {
            get {
                return ResourceManager.GetString("emailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail(login).
        /// </summary>
        public static string emailLogin {
            get {
                return ResourceManager.GetString("emailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the end of the billing period..
        /// </summary>
        public static string endPayPeriod {
            get {
                return ResourceManager.GetString("endPayPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description for the group..
        /// </summary>
        public static string enterDescripGroup {
            get {
                return ResourceManager.GetString("enterDescripGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the type of payments for the following billing period.
        /// </summary>
        public static string enterTypePay {
            get {
                return ResourceManager.GetString("enterTypePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the e-mail used as a login..
        /// </summary>
        public static string fillEmail {
            get {
                return ResourceManager.GetString("fillEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the group name..
        /// </summary>
        public static string fillGroupName {
            get {
                return ResourceManager.GetString("fillGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your first name..
        /// </summary>
        public static string fillName {
            get {
                return ResourceManager.GetString("fillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the password..
        /// </summary>
        public static string fillPassword {
            get {
                return ResourceManager.GetString("fillPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your surname..
        /// </summary>
        public static string fillSurname {
            get {
                return ResourceManager.GetString("fillSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you forget your password?.
        /// </summary>
        public static string forgot {
            get {
                return ResourceManager.GetString("forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The groups where I&apos;m a member.
        /// </summary>
        public static string groupsIn {
            get {
                return ResourceManager.GetString("groupsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string IDowner {
            get {
                return ResourceManager.GetString("IDowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail format..
        /// </summary>
        public static string invalidEmail {
            get {
                return ResourceManager.GetString("invalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number..
        /// </summary>
        public static string invalidePhone {
            get {
                return ResourceManager.GetString("invalidePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of all groups.
        /// </summary>
        public static string listAllGroups {
            get {
                return ResourceManager.GetString("listAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of articles.
        /// </summary>
        public static string listArticle {
            get {
                return ResourceManager.GetString("listArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of my groups.
        /// </summary>
        public static string listOfMyGroups {
            get {
                return ResourceManager.GetString("listOfMyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string log_In {
            get {
                return ResourceManager.GetString("log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost password.
        /// </summary>
        public static string lostPassword {
            get {
                return ResourceManager.GetString("lostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string myProfile {
            get {
                return ResourceManager.GetString("myProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of event.
        /// </summary>
        public static string nameEvent {
            get {
                return ResourceManager.GetString("nameEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New article.
        /// </summary>
        public static string newArticle {
            get {
                return ResourceManager.GetString("newArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New event.
        /// </summary>
        public static string newEvent {
            get {
                return ResourceManager.GetString("newEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        public static string newGroup {
            get {
                return ResourceManager.GetString("newGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of users.
        /// </summary>
        public static string numberOfUsers {
            get {
                return ResourceManager.GetString("numberOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation..
        /// </summary>
        public static string passwordConfirm {
            get {
                return ResourceManager.GetString("passwordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment period.
        /// </summary>
        public static string paymentPeriod {
            get {
                return ResourceManager.GetString("paymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the description of the group..
        /// </summary>
        public static string pleaseFillDescrip {
            get {
                return ResourceManager.GetString("pleaseFillDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the e-mail used as a login..
        /// </summary>
        public static string pleaseFillInEmail {
            get {
                return ResourceManager.GetString("pleaseFillInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the name of the group..
        /// </summary>
        public static string pleaseFillName {
            get {
                return ResourceManager.GetString("pleaseFillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string reg {
            get {
                return ResourceManager.GetString("reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration form.
        /// </summary>
        public static string regForm {
            get {
                return ResourceManager.GetString("regForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
